/**
 * @fileoverview Central Type Definitions Export
 * Exports all TypeScript types and interfaces from a single location
 *
 * @author Air Niugini Development Team
 * @version 1.0.0
 * @since 2025-09-30
 */

// ===== STATE TYPES =====
export type {
  LoadingState,
  SubmissionState,
  PaginationState,
  FilterState,
  SortState,
  ModalState,
  PilotFormState,
  CertificationFormState,
  LeaveRequestFormState,
  BulkCertificationState,
  DashboardStatsState,
  CalendarState,
  SettingsState,
  AnalyticsDashboardState,
  LeaveApprovalState,
  SidebarState,
  ConflictCheckState,
  ExportState,
  ToastState,
  SearchPanelState,
  ViewToggleState,
} from './state.types';

// ===== API TYPES =====
export type {
  ApiResponse,
  ApiError,
  PaginationParams,
  FilterParams,
  PilotData,
  PilotWithRelations,
  CreatePilotRequest,
  UpdatePilotRequest,
  PilotListResponse,
  PilotDetailResponse,
  CertificationData,
  CertificationWithRelations,
  UpsertCertificationRequest,
  BulkCertificationRequest,
  BulkCertificationResult,
  ExpiringCertificationsParams,
  CertificationListResponse,
  LeaveRequestData,
  LeaveRequestWithRelations,
  CreateLeaveRequest,
  UpdateLeaveStatusRequest,
  LeaveConflictCheckRequest,
  LeaveConflict,
  LeaveConflictCheckResponse,
  LeaveRequestListResponse,
  CheckTypeData,
  CheckTypeListResponse,
  ContractTypeData,
  ContractTypeListResponse,
  SettingData,
  UpdateSettingRequest,
  SettingsListResponse,
  DashboardStatsResponse,
  PilotAnalyticsParams,
  CertificationAnalyticsParams,
  LeaveAnalyticsParams,
  GenerateReportRequest,
  GenerateReportResponse,
  UserData,
  LoginRequest,
  LoginResponse,
  CurrentUserResponse,
  ChartData,
  TimeSeriesPoint,
  ChartExportRequest,
} from './api.types';

// ===== DASHBOARD TYPES =====
export type {
  DashboardCard,
  PilotStatistics,
  CertificationStatistics,
  LeaveStatistics,
  ActivityItem,
  DashboardAlert,
  ExpiringCertificationSummary,
  PilotSummary as DashboardPilotSummary,
  FleetReadiness,
  ComplianceOverview as DashboardComplianceOverview,
  DashboardChartData,
  QuickAction,
  DashboardWidget,
  DashboardLayout,
  DashboardRefreshStatus,
  SystemStatus,
  DashboardFilters,
  DashboardSnapshot,
} from './dashboard.types';

// ===== FORM TYPES =====
export type {
  FormFieldError,
  FormValidationResult,
  PilotAddFormData,
  PilotEditFormData,
  PilotFilterFormData,
  PilotBulkActionFormData,
  CertificationFormData,
  BulkCertificationFormData,
  CertificationFilterFormData,
  LeaveRequestFormData,
  LeaveRequestEditFormData,
  LeaveApprovalFormData,
  LeaveFilterFormData,
  GeneralSettingsFormData,
  NotificationSettingsFormData,
  UserSettingsFormData,
  ReportGenerationFormData,
  ReportFilterFormData,
  GlobalSearchFormData,
  AdvancedSearchFormData,
  LoginFormData,
  PasswordResetFormData,
  PasswordChangeFormData,
  FormState,
  FormFieldProps,
  SelectOption,
  DateRangeValue,
  FileUploadValue,
  MultiSelectValue,
  CheckboxGroupValue,
  FormSubmitResult,
} from './forms.types';

// ===== ANALYTICS TYPES =====
export type {
  ChartColors,
  ChartOptions,
  PilotAnalytics,
  CertificationAnalytics,
  LeaveAnalytics,
  FleetAnalytics,
  TrendAnalytics,
  RiskAnalytics,
  PieChartData,
  BarChartData,
  LineChartData,
  DoughnutChartData,
  InteractiveChartProps,
  ChartFilter,
  ExportOptions,
  DashboardLayout as AnalyticsDashboardLayout,
  RealtimeUpdate,
  AnalyticsPerformance,
  AnalyticsQuery,
  AnalyticsResult,
  AnalyticsAlert,
  KPIMetric,
} from './analytics';

// ===== PDF REPORT TYPES =====
export type {
  PDFReportMetadata,
  PDFReportOptions,
  ComplianceOverview,
  ExpirationBreakdown,
  ComplianceByCategory,
  PilotComplianceStatus,
  ComplianceReportData,
  PilotSummary,
  TrainingHistoryEntry,
  DetailedPilotRecord,
  PilotReportData,
  FleetRosterAnalysis,
  CaptainQualification,
  LeaveAnalysis,
  OperationalReadiness,
  FleetManagementReportData,
  FleetStatistics,
  AirNiuginiStyles,
  PDFTableConfig,
  PDFChartConfig,
  PDFReportType,
  PDFReportData,
  PDFGenerationRequest,
  PDFGenerationResponse,
} from './pdf-reports';

// ===== CONSTANTS =====
export { AIR_NIUGINI_COLORS } from './analytics';

// ===== RE-EXPORT SCHEMAS FOR VALIDATION =====
// Users can import schemas from '@/schemas/*' directly
// Individual schemas and types are exported from their respective files
