import { NextRequest, NextResponse } from 'next/server';
import { renderToBuffer } from '@react-pdf/renderer';
import { createElement } from 'react';
import { getLeaveRequestsByRosterPeriodAdmin } from '@/lib/leave-service';
import { getRosterPeriodFromDate, getFutureRosterPeriods } from '@/lib/roster-utils';
import {
  createRosterLeaveReportDocument,
  createRosterLeaveReportData,
  generateRosterLeaveReportFilename,
} from '@/lib/pdf-roster-leave-report';

/**
 * Generate and download Roster Leave Planning PDF Report
 */
export async function POST(request: NextRequest) {
  try {
    console.log('🎯 Starting roster leave PDF report generation...');

    const body = await request.json();
    const { rosterPeriod, generatedBy } = body;

    // Validation
    if (!rosterPeriod) {
      return NextResponse.json(
        { success: false, error: 'Roster period is required' },
        { status: 400 }
      );
    }

    if (!generatedBy) {
      return NextResponse.json(
        { success: false, error: 'Generated by information is required' },
        { status: 400 }
      );
    }

    console.log(`📊 Generating report for roster period: ${rosterPeriod}`);

    // Find the roster period details
    const futureRosters = getFutureRosterPeriods(12);
    const selectedRoster = futureRosters.find((r) => r.code === rosterPeriod);

    if (!selectedRoster) {
      return NextResponse.json(
        { success: false, error: 'Invalid roster period selected' },
        { status: 404 }
      );
    }

    // Fetch leave requests for the roster period
    console.log(`📋 Fetching leave requests for ${rosterPeriod}...`);
    const leaveRequests = await getLeaveRequestsByRosterPeriodAdmin(rosterPeriod);

    console.log(`✅ Found ${leaveRequests.length} leave requests`);

    // Create report data
    const reportData = createRosterLeaveReportData(selectedRoster, leaveRequests, generatedBy);

    // Generate PDF
    console.log('🔄 Generating PDF document...');
    const pdfBuffer = await renderToBuffer(createRosterLeaveReportDocument(reportData));

    console.log('✅ PDF generated successfully');

    // Generate filename
    const filename = generateRosterLeaveReportFilename(rosterPeriod);

    // Return PDF as downloadable file
    return new NextResponse(new Uint8Array(pdfBuffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': pdfBuffer.length.toString(),
        'Cache-Control': 'no-cache',
      },
    });
  } catch (error) {
    console.error('❌ Error generating roster leave PDF report:', error);

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to generate PDF report',
      },
      { status: 500 }
    );
  }
}

/**
 * Get available roster periods for report generation
 */
export async function GET(request: NextRequest) {
  try {
    console.log('📅 Fetching available roster periods...');

    const url = new URL(request.url);
    const monthsAhead = parseInt(url.searchParams.get('months') || '12');

    const futureRosters = getFutureRosterPeriods(monthsAhead);

    // Format roster periods for dropdown display
    const rosterOptions = futureRosters.map((roster) => ({
      value: roster.code,
      label: `${roster.code}: ${roster.startDate.toLocaleDateString()} - ${roster.endDate.toLocaleDateString()}`,
      startDate: roster.startDate.toISOString(),
      endDate: roster.endDate.toISOString(),
      daysRemaining: roster.daysRemaining,
    }));

    return NextResponse.json({
      success: true,
      data: rosterOptions,
    });
  } catch (error) {
    console.error('❌ Error fetching roster periods:', error);

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to fetch roster periods',
      },
      { status: 500 }
    );
  }
}
